### ISSUE TITLE
Exception thrown in activate function

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/zendesk-web-widget#2]
Our remote monitoring indicates that some users receive `Cannot read property 'length' of null` exceptions from the element's `activate()` function.
Observed OS/browsers for which the exception was reported:
- Chrome 52 on MacOS
- Chrome 50 on Win 7

**Comment by ankon** [comment]
The problem was that I mixed up the `querySelector` and `querySelectorAll` functions - 1ce24f2 fixes that.
